import pytest
from basetest import BaseMIPFederationTest


"""
This pytest test was customized from the version automatically generated by TestProject
    Project: Test of the MIP federations
    Test: QA federation
    Generated by: Sebastien Tourbier (sebastien.tourbier@chuv.ch)
    Generated on 02/10/2023, 10:00:25
    Modified by: Sebastien Tourbier (sebastien.tourbier@chuv.ch)
    Last modification: 03/16/2023
"""


@pytest.mark.parametrize("selenium_driver", ["https://qa.hbpmip.link/"], indirect=True)
class TestMIPQAFederation(BaseMIPFederationTest):
    def test_login_and_accept_terms(self):
        """Test login and accept terms on the public MIP."""
        super().test_login_and_accept_terms()

    def test_data(self):
        """Integration tests (data) of the MIP QA Federation."""
        super().test_data()
