import pytest
from basetest import BaseMIPFederationTest


"""
This pytest test was customized from the version automatically generated by TestProject
    Project: Test of the MIP federations
    Test: Public MIP
    Generated by: Sebastien Tourbier (sebastien.tourbier@chuv.ch)
    Generated on 02/10/2023, 10:00:37
    Modified by: Sebastien Tourbier (sebastien.tourbier@chuv.ch)
    Last modification: 03/16/2023
"""


@pytest.mark.parametrize("selenium_driver", ["https://hbpmip.link/"], indirect=True)
class TestPublicMIP(BaseMIPFederationTest):
    def test_login_and_accept_terms(self):
        """Test login and accept terms on the public MIP."""
        super().test_login_and_accept_terms()

    def test_data(self):
        """Integration tests (data) of the public MIP."""
        super().test_data()
