import time

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
import project_parameters
import pytest


"""
This pytest test was customized from the version automatically generated by TestProject
    Project: Test of the MIP federations
    Test: Public MIP
    Generated by: Sebastien Tourbier (sebastien.tourbier@chuv.ch)
    Generated on 02/10/2023, 10:00:37
    Modified by: Sebastien Tourbier (sebastien.tourbier@chuv.ch)
    Last modification: 07/03/2023
"""


def set_chrome_options() -> None:
    """Sets chrome options for Selenium.

    Chrome options for headless browser is enabled.
    """
    chrome_options = Options()
    # chrome_options.add_argument("--headless")
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-dev-shm-usage")
    chrome_options.add_argument("--window-size=1920,1080")
    chrome_prefs = {}
    chrome_options.experimental_options["prefs"] = chrome_prefs
    chrome_prefs["profile.default_content_settings"] = {"images": 2}
    return chrome_options


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(
        service=Service(ChromeDriverManager().install()), options=set_chrome_options()
    )
    driver.maximize_window()
    driver.implicitly_wait(20)
    yield driver
    driver.quit()


def test_main(driver):
    """Histogram of two variable per datasets."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "https://hbpmip.link/"

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f"{ApplicationURL}")

    # 3. Click 'Login'
    login = driver.find_element(By.XPATH, "//button[. = 'Login']")
    login.click()

    # 4. Click 'username'
    username = driver.find_element(By.CSS_SELECTOR, "#username")
    username.click()

    # 5. Type '{project_parameters.UserID}' in 'username'
    username = driver.find_element(By.CSS_SELECTOR, "#username")
    username.send_keys(f"{project_parameters.UserID}")

    # 6. Click 'password'
    password = driver.find_element(By.CSS_SELECTOR, "#password")
    password.click()

    # 7. Type '{project_parameters.UserPWD}' in 'password'
    password = driver.find_element(By.CSS_SELECTOR, "#password")
    password.send_keys(f"{project_parameters.UserPWD}")

    # 8. Click 'login'
    login1 = driver.find_element(By.CSS_SELECTOR, "#kc-login")
    login1.click()

    # 2. Click '×' if needed
    try:
        _ = driver.find_element(By.XPATH, "//span[. = '×']")
        _.click()
    except Exception:
        pass

    # 9. Click 'Dementia' /html/body/div[8]/main/div/div[1]/div/div[1]/div[1]/div[1]/div/div/a[1]
    datasets = driver.find_element(By.XPATH, "//div[@id='pathology-select']/div/button")
    datasets.click()

    # 10. Click 'Mentalhealth'
    dementia = driver.find_element(By.LINK_TEXT, "mentalhealth v7")
    dementia.click()

    # 11. Click 'OK'
    ok = driver.find_element(By.XPATH, "//button[. = 'OK']")
    ok.click()

    # 12. Click 'Datasets'
    datasets = driver.find_element(By.CSS_SELECTOR, "#dropdown-basic")
    datasets.click()

    # 13. Click 'default-synth_mh_wk2'
    time.sleep(3)
    default_synth_mh_wk2 = driver.find_element(By.CSS_SELECTOR, "#default-synth_mh_wk2")
    default_synth_mh_wk2.click()

    # 14. Click 'default-synth_mh_wk3'
    default_synth_mh_wk3 = driver.find_element(By.CSS_SELECTOR, "#default-synth_mh_wk3")
    default_synth_mh_wk3.click()

    # 15. Click 'default-synth_mh_wk4'
    default_synth_mh_wk4 = driver.find_element(By.CSS_SELECTOR, "#default-synth_mh_wk4")
    default_synth_mh_wk4.click()

    # 16. Click 'default-synth_mh_wk5'
    default_synth_mh_wk5 = driver.find_element(By.CSS_SELECTOR, "#default-synth_mh_wk5")
    default_synth_mh_wk5.click()

    # 17. Click 'Left opercular part of the inferior f...'
    left_opercular_part_of_the_inferior_f_ = driver.find_element(
        By.XPATH,
        "//*[name()='circle'][. = 'Left opercular part of the inferior frontal gyrus\n']",
    )
    left_opercular_part_of_the_inferior_f_.click()

    # 18. Is  the div containing the histogram of 'Left opercular part of the inferior f...' generated?
    histogram_of_leftopifgopercularpartof_ = driver.find_element(
        By.XPATH,
        "//div[contains(@id,'bar-graph-left-opercular-part-of-the-inferior-frontal-gyrus')]",
    )
    assert histogram_of_leftopifgopercularpartof_

    # 19. Click 'Right occipital fusiform gyrus'
    right_occipital_fusiform_gyrus = driver.find_element(
        By.XPATH, "//*[name()='circle'][. = 'Right occipital fusiform gyrus\n']"
    )
    right_occipital_fusiform_gyrus.click()

    # 20. Is the div containing the histogram of 'Right occipital fusiform gyrus' generated?
    histogram_of_rightofugoccipitalfusifo_ = driver.find_element(
        By.XPATH, "//div[contains(@id,'bar-graph-right-occipital-fusiform-gyrus')]"
    )
    assert histogram_of_rightofugoccipitalfusifo_

    # 21. Click 'Datasets'
    datasets = driver.find_element(By.CSS_SELECTOR, "#dropdown-basic")
    datasets.click()

    # 22. Click 'default-synth_mh_wk1'
    default_synth_mh_wk1 = driver.find_element(By.CSS_SELECTOR, "#default-synth_mh_wk1")
    default_synth_mh_wk1.click()

    # 23. Click 'default-synth_mh_wk2'
    default_synth_mh_wk2 = driver.find_element(By.CSS_SELECTOR, "#default-synth_mh_wk2")
    default_synth_mh_wk2.click()

    # 24. Click 'Sepa: afraid of being at home alone (...'
    sepa_colon_afraid_of_being_at_home_alone_ = driver.find_element(
        By.XPATH,
        "//*[name()='circle'][. = 'Sepa: afraid of being at home alone (youth)\nNightmares about separation from attachment figures in the past 4 weeks']",
    )
    sepa_colon_afraid_of_being_at_home_alone_.click()

    # 25. Is the div containing the histogram of 'Sepa: afraid of being at home alone (...' generated?
    histogram_of_sa3h = driver.find_element(
        By.XPATH,
        "//div[contains(@id,'bar-graph-sepa-afraid-of-being-at-home-alone-youth')]",
    )
    assert histogram_of_sa3h

    # 26. Click 'Right transverse temporal gyrus'
    right_transverse_temporal_gyrus = driver.find_element(
        By.XPATH, "//*[name()='circle'][. = 'Right transverse temporal gyrus\n']"
    )
    right_transverse_temporal_gyrus.click()

    # 27. Is the div containing the histogram of 'Right transverse temporal gyrus' generated?
    histogram_of_rightttgtransversetempor_ = driver.find_element(
        By.XPATH, "//div[contains(@id,'bar-graph-right-transverse-temporal-gyrus')]"
    )
    assert histogram_of_rightttgtransversetempor_

    # 28. Click 'Datasets'
    datasets = driver.find_element(By.CSS_SELECTOR, "#dropdown-basic")
    datasets.click()

    # 29. Click 'default-synth_mh_wk2'
    default_synth_mh_wk2 = driver.find_element(By.CSS_SELECTOR, "#default-synth_mh_wk2")
    default_synth_mh_wk2.click()

    # 30. Click 'default-synth_mh_wk3'
    default_synth_mh_wk3 = driver.find_element(By.CSS_SELECTOR, "#default-synth_mh_wk3")
    default_synth_mh_wk3.click()

    # 31. Click 'Right posterior cingulate gyrus1'
    right_posterior_cingulate_gyrus1 = driver.find_element(
        By.XPATH, "//*[name()='circle'][. = 'Right posterior cingulate gyrus\n']"
    )
    right_posterior_cingulate_gyrus1.click()

    # 32. Is the div containing the histogram of 'Right posterior cingulate gyrus1' generated?
    histogram_of_rightpcggposteriorcingul_ = driver.find_element(
        By.XPATH, "//div[contains(@id,'bar-graph-right-posterior-cingulate-gyrus')]"
    )
    assert histogram_of_rightpcggposteriorcingul_

    # 33. Click 'Sepa: any concerns about separations?...'
    sepa_colon_any_concerns_about_separations_question_mark_ = driver.find_element(
        By.XPATH,
        "//*[name()='circle'][. = 'Sepa: any concerns about separations? (youth)\nConcern about separation over the past 4 weeks']",
    )
    sepa_colon_any_concerns_about_separations_question_mark_.click()

    # 34. Is the div containing the histogram of 'Sepa: any concerns about separations?...' generated?
    histogram_of_sa2 = driver.find_element(
        By.XPATH,
        "//div[contains(@id,'bar-graph-sepa-any-concerns-about-separations-youth')]",
    )
    assert histogram_of_sa2

    # 35. Click 'Datasets'
    datasets = driver.find_element(By.CSS_SELECTOR, "#dropdown-basic")
    datasets.click()

    # 36. Click 'default-synth_mh_wk3'
    default_synth_mh_wk3 = driver.find_element(By.CSS_SELECTOR, "#default-synth_mh_wk3")
    default_synth_mh_wk3.click()

    # 37. Click 'default-synth_mh_wk4'
    default_synth_mh_wk4 = driver.find_element(By.CSS_SELECTOR, "#default-synth_mh_wk4")
    default_synth_mh_wk4.click()

    # 38. Click 'Right superior temporal gyrus'
    right_superior_temporal_gyrus = driver.find_element(
        By.XPATH, "//*[name()='circle'][. = 'Right superior temporal gyrus\n']"
    )
    right_superior_temporal_gyrus.click()

    # 39. Is the div containing the histogram of 'Right superior temporal gyrus' generated?
    histogram_of_rightstgsuperiortemporal_ = driver.find_element(
        By.XPATH, "//div[contains(@id,'bar-graph-right-superior-temporal-gyrus')]"
    )
    assert histogram_of_rightstgsuperiortemporal_

    # 40. Click 'Right inferior lateral ventricle1'
    right_inferior_lateral_ventricle1 = driver.find_element(
        By.XPATH, "//*[name()='circle'][. = 'Right inferior lateral ventricle\n']"
    )
    right_inferior_lateral_ventricle1.click()

    # 41. Is the div containing the histogram of 'Right inferior lateral ventricle1' generated?
    histogram_of_rightinflatvent = driver.find_element(
        By.XPATH, "//div[contains(@id,'bar-graph-right-inferior-lateral-ventricle')]"
    )
    assert histogram_of_rightinflatvent

    # 42. Click 'Datasets'
    datasets = driver.find_element(By.CSS_SELECTOR, "#dropdown-basic")
    datasets.click()

    # 43. Click 'default-synth_mh_wk4'
    default_synth_mh_wk4 = driver.find_element(By.CSS_SELECTOR, "#default-synth_mh_wk4")
    default_synth_mh_wk4.click()

    # 44. Click 'default-synth_mh_wk5'
    default_synth_mh_wk5 = driver.find_element(By.CSS_SELECTOR, "#default-synth_mh_wk5")
    default_synth_mh_wk5.click()

    # 45. Click 'Right entorhinal area'
    right_entorhinal_area = driver.find_element(
        By.XPATH, "//*[name()='circle'][. = 'Right entorhinal area\n']"
    )
    right_entorhinal_area.click()

    # 46. Is the div containing the histogram of 'Right entorhinal area' generated?
    histogram_of_rightententorhinalarea = driver.find_element(
        By.XPATH, "//div[contains(@id,'bar-graph-right-entorhinal-area')]"
    )
    assert histogram_of_rightententorhinalarea

    # 47. Click 'Left subcallosal area'
    left_subcallosal_area = driver.find_element(
        By.XPATH, "//*[name()='circle'][. = 'Left subcallosal area\n']"
    )
    left_subcallosal_area.click()

    # 48. Is the div containing the histogram of 'Left subcallosal area' generated?
    histogram_of_leftscasubcallosalarea = driver.find_element(
        By.XPATH, "//div[contains(@id,'bar-graph-left-subcallosal-area')]"
    )
    assert histogram_of_leftscasubcallosalarea
