name: Integration Tests of MIP Federations

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Runs "at 6:55am every day" (see https://crontab.guru)
    - cron: '55 6 * * *'

jobs:
  build-test-report:
    runs-on: ubuntu-latest
    environment: Integration test pipeline  # TO INHERIT SECRETS
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Setup project parameters
        run: |
          cat << EOF > $(pwd)/tests/project_parameters.py
          UserID = "$EBRAINSUSERID"
          UserPWD = "$EBRAINSUSERPWD"
          EOF
          cat $(pwd)/tests/project_parameters.py
        env:
          EBRAINSUSERID: ${{ secrets.EBRAINSUSERID }}
          EBRAINSUSERPWD: ${{ secrets.EBRAINSUSERPWD }} 
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: pytest_mip:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Get current date
        run: |
          echo "current_date=$(date +%d-%m-%Y-%H-%M)" >> $GITHUB_ENV
          echo "current_date_fmt=$(date '+%d-%m-%Y %H:%M')" >> $GITHUB_ENV
      -
        name: Run integration tests of the up-and-running MIP federations
        run: |
          mkdir -p report/report-${{ env.current_date }}
          docker run -v $(pwd)/report/report-${{ env.current_date }}:/app/report -t pytest_mip .
      -
        name: Rename report.html to index.html for GitHub Page
        if: success() || failure()
        run: |
          mv $(pwd)/report/report-${{ env.current_date }}/report.html $(pwd)/report/report-${{ env.current_date }}/index.html
      - 
        name: Install JQ
        run: sudo apt-get install jq
      - 
        name: Update Reports JSON
        run: |
              # read the existing JSON content
              json=$(curl -s "https://hbpmedical.github.io/pytest-mip/reports.json")

              # create a new JSON object to append
              new_record=$(echo "{\"date\": \"${{ env.current_date_fmt }}\", \"link\": \"https://hbpmedical.github.io/pytest-mip/report-${{ env.current_date }}\", \"junitxml\": \"https://hbpmedical.github.io/pytest-mip/report-${{ env.current_date }}/junit-report.xml\", \"status\": \"$?\"}")

              # append the new record to the "reports" array
              json=$(echo $json | jq ".reports += [$new_record]")

              # write the updated JSON content back to the file
              echo $json > $(pwd)/report/reports.json
      - 
        name: Deploy report to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        if: success() || failure()
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: report
          keep_files: true
