name: Integration Tests of MIP Federations

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Runs "at 6:55am every day" (see https://crontab.guru)
    - cron: '55 6 * * *'

jobs:
  build-test-report:
    runs-on: ubuntu-latest
    environment: Integration test pipeline  # TO INHERIT SECRETS
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Setup project parameters
        run: |
          cat << EOF > $(pwd)/tests/project_parameters.py
          UserID = "$EBRAINSUSERID"
          UserPWD = "$EBRAINSUSERPWD"
          EOF
          cat $(pwd)/tests/project_parameters.py
        env:
          EBRAINSUSERID: ${{ secrets.EBRAINSUSERID }}
          EBRAINSUSERPWD: ${{ secrets.EBRAINSUSERPWD }} 
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: pytest_mip:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Get current date
        run: echo "current_date=$(date +%d-%m-%Y)" >> $GITHUB_ENV
      -
        name: Run integration tests of the up-and-running MIP federations
        run: |
          mkdir -p report-${{ env.current_date }}
          docker run -v $(pwd)/report-${{ env.current_date }}:/app/report -t pytest_mip .
      -
        name: Rename report.html to index.html for GitHub Page
        if: success() || failure()
        run: |
          mv $(pwd)/report-${{ env.current_date }}/report.html $(pwd)/report-${{ env.current_date }}/index.html
      -
        name: Generate JSON file with information about the test run for table in main index.html
        if: success() || failure()
        run: |
          # 
          cat << EOF > $(pwd)/report-${{ env.current_date }}/integration_test_info.json
          {
            "date": "${{ env.current_date }}",
            "link": "report-${{ env.current_date }}/index.html",
            "status": "$?"
          }
          EOF
          cat $(pwd)/report-${{ env.current_date }}/integration_test_info.json
      - 
        name: Deploy report to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        if: success() || failure()
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: report-${{ env.current_date }}
          target_dir: report-${{ env.current_date }}
          force_orphan: true
          clean: false
